problems = [(5,
('Millennium Falcon', 'Yamato', 'Sidonia'),
('tachyon cannon', 'warp field meter', 'D-EFT', 'alien life detector'),
{'Millennium Falcon': ('tachyon cannon', 'warp field meter', 'alien life detector'), 'Sidonia': ('D-EFT',), 'Yamato': ('D-EFT',)},
{'tachyon cannon': (2, 2, 1), 'warp field meter': (2, 1, 2), 'D-EFT': (3, 4, 4), 'alien life detector': (4, 3, 3)},
{(0, 1, 2): ('alien life detector', 'D-EFT', 'warp field meter'), (3, 3, 0): ('tachyon cannon',), (2, 4, 4): ('alien life detector', 'tachyon cannon', 'warp field meter'), (4, 2, 3): ('tachyon cannon', 'D-EFT', 'alien life detector'), (3, 0, 2): ('warp field meter',), (1, 1, 2): ('warp field meter', 'alien life detector', 'D-EFT'), (4, 3, 2): ('D-EFT', 'tachyon cannon'), (4, 2, 4): ('tachyon cannon', 'D-EFT', 'alien life detector'), (4, 2, 2): ('tachyon cannon', 'warp field meter'), (0, 0, 0): ('warp field meter',)},
{'Millennium Falcon': (4, 1, 4), 'Yamato': (0, 1, 4), 'Sidonia': (2, 3, 4)},
((-1, 0, 3), (4, -1, 1), (-1, 1, 3), (2, -1, 3), (-1, 1, 3)),
50,
206,
)
,
(6,
('Rama', 'Galactica', 'Apollo', 'Death Star'),
('D-EFT', 'alien life detector', 'reconnaissance USV', 'QAS-2', 'wormhole detector'),
{'Rama': ('D-EFT',), 'Apollo': ('alien life detector', 'QAS-2'), 'Death Star': ('reconnaissance USV', 'wormhole detector'), 'Galactica': ('QAS-2',)},
{'D-EFT': (2, 3, 3), 'alien life detector': (0, 5, 3), 'reconnaissance USV': (4, 3, 0), 'QAS-2': (3, 1, 1), 'wormhole detector': (1, 1, 2)},
{(1, 2, 0): ('D-EFT',), (0, 3, 2): ('D-EFT', 'wormhole detector'), (5, 2, 1): ('QAS-2', 'wormhole detector', 'alien life detector'), (1, 5, 2): ('QAS-2', 'D-EFT'), (4, 3, 3): ('alien life detector',), (0, 2, 3): ('QAS-2', 'alien life detector'), (0, 5, 1): ('D-EFT', 'alien life detector', 'QAS-2'), (2, 4, 0): ('wormhole detector', 'QAS-2', 'reconnaissance USV'), (2, 3, 4): ('QAS-2', 'wormhole detector'), (3, 5, 4): ('QAS-2', 'reconnaissance USV', 'alien life detector'), (1, 4, 4): ('QAS-2', 'alien life detector'), (3, 2, 1): ('D-EFT', 'alien life detector', 'reconnaissance USV'), (5, 0, 1): ('wormhole detector',)},
{'Rama': (1, 2, 2), 'Galactica': (3, 5, 3), 'Apollo': (5, 3, 0), 'Death Star': (5, 4, 4)},
((5, 1, -1), (4, 0, -1), (4, -1, 5), (-1, 1, 5), (-1, 0, 5), (-1, 4, 1), (4, -1, 4)),
72,
257,
)
,
(7,
('Sidonia', 'Galactica', 'Rama', 'Millennium Falcon', 'Death Star'),
('X-ray scanner', 'reconnaissance USV', 'alien life detector', 'tachyon cannon', 'hyperspace probe', 'plasmoid camera'),
{'Millennium Falcon': ('X-ray scanner', 'hyperspace probe'), 'Rama': ('reconnaissance USV',), 'Death Star': ('alien life detector',), 'Galactica': ('tachyon cannon',), 'Sidonia': ('plasmoid camera',)},
{'X-ray scanner': (2, 4, 2), 'reconnaissance USV': (3, 4, 1), 'alien life detector': (1, 0, 6), 'tachyon cannon': (2, 5, 0), 'hyperspace probe': (0, 3, 3), 'plasmoid camera': (6, 4, 3)},
{(4, 6, 4): ('tachyon cannon',), (1, 5, 4): ('tachyon cannon', 'reconnaissance USV'), (2, 5, 1): ('plasmoid camera', 'tachyon cannon'), (2, 2, 3): ('plasmoid camera',), (5, 0, 2): ('tachyon cannon',), (2, 0, 3): ('plasmoid camera', 'reconnaissance USV', 'alien life detector'), (3, 4, 2): ('reconnaissance USV',), (3, 2, 3): ('alien life detector', 'tachyon cannon', 'X-ray scanner'), (2, 4, 6): ('alien life detector',), (4, 4, 0): ('X-ray scanner', 'tachyon cannon', 'reconnaissance USV'), (6, 0, 1): ('plasmoid camera', 'hyperspace probe'), (2, 5, 6): ('plasmoid camera', 'tachyon cannon'), (1, 0, 5): ('tachyon cannon',), (5, 6, 1): ('alien life detector', 'X-ray scanner'), (6, 4, 5): ('X-ray scanner', 'plasmoid camera', 'alien life detector'), (3, 1, 3): ('alien life detector', 'tachyon cannon')},
{'Sidonia': (2, 4, 4), 'Galactica': (3, 4, 0), 'Rama': (4, 2, 0), 'Millennium Falcon': (2, 5, 3), 'Death Star': (3, 5, 4)},
((5, -1, 0), (4, -1, 2), (-1, 1, 4), (4, 1, -1), (6, -1, 0), (1, 2, -1), (5, 5, -1), (0, 4, -1), (4, 5, -1)),
98,
309,
)
,
(8,
('Millennium Falcon', 'Death Star', 'Rama', 'Soyuz', 'Galactica', 'Yamato'),
('D-EFT', 'rangefinder', 'hyperspace probe', 'QAS-2', 'X-ray scanner', 'plasmoid camera', 'wormhole detector'),
{'Rama': ('D-EFT', 'plasmoid camera'), 'Millennium Falcon': ('rangefinder', 'hyperspace probe', 'QAS-2'), 'Yamato': ('X-ray scanner',), 'Death Star': ('wormhole detector',), 'Soyuz': ('plasmoid camera',), 'Galactica': ('rangefinder',)},
{'D-EFT': (6, 5, 7), 'rangefinder': (7, 6, 0), 'hyperspace probe': (4, 6, 1), 'QAS-2': (4, 2, 4), 'X-ray scanner': (2, 6, 2), 'plasmoid camera': (4, 5, 5), 'wormhole detector': (7, 4, 0)},
{(3, 4, 0): ('D-EFT',), (6, 4, 1): ('D-EFT', 'plasmoid camera', 'X-ray scanner'), (0, 0, 1): ('rangefinder', 'hyperspace probe', 'QAS-2'), (4, 7, 6): ('rangefinder',), (4, 6, 2): ('rangefinder', 'X-ray scanner'), (0, 5, 2): ('X-ray scanner', 'hyperspace probe'), (2, 5, 5): ('D-EFT', 'wormhole detector', 'plasmoid camera'), (3, 1, 5): ('rangefinder',), (0, 4, 5): ('X-ray scanner', 'rangefinder'), (3, 5, 5): ('hyperspace probe', 'D-EFT', 'X-ray scanner'), (5, 7, 6): ('wormhole detector',), (6, 4, 2): ('hyperspace probe', 'D-EFT', 'rangefinder'), (7, 2, 2): ('hyperspace probe', 'X-ray scanner', 'wormhole detector'), (5, 2, 5): ('D-EFT', 'hyperspace probe'), (0, 7, 3): ('wormhole detector', 'QAS-2'), (6, 1, 3): ('D-EFT', 'X-ray scanner'), (7, 7, 0): ('plasmoid camera',), (2, 2, 3): ('plasmoid camera', 'hyperspace probe'), (3, 2, 1): ('rangefinder', 'hyperspace probe', 'X-ray scanner')},
{'Millennium Falcon': (2, 4, 1), 'Death Star': (2, 1, 0), 'Rama': (2, 2, 2), 'Soyuz': (6, 6, 6), 'Galactica': (3, 5, 2), 'Yamato': (4, 7, 4)},
((7, 1, -1), (5, 1, -1), (5, 1, -1), (6, -1, 0), (1, -1, 7), (-1, 4, 4), (4, -1, 3), (-1, 7, 1), (4, 3, -1), (1, -1, 3), (6, 2, -1), (5, -1, 2)),
128,
363,
)
,
(9,
('Apollo', 'Rama', 'Galactica', 'Enterprise', 'Rocinante', 'Millennium Falcon', 'Soyuz'),
('alien life detector', 'QAS-2', 'wormhole detector', 'spectrograph', 'D-EFT', 'tachyon cannon', 'warp field meter', 'hyperspace probe'),
{'Apollo': ('alien life detector', 'spectrograph', 'tachyon cannon'), 'Enterprise': ('QAS-2', 'D-EFT'), 'Rocinante': ('wormhole detector',), 'Galactica': ('warp field meter', 'hyperspace probe'), 'Rama': ('D-EFT',), 'Millennium Falcon': ('wormhole detector',), 'Soyuz': ('alien life detector',)},
{'alien life detector': (8, 6, 0), 'QAS-2': (7, 7, 1), 'wormhole detector': (6, 6, 3), 'spectrograph': (8, 6, 5), 'D-EFT': (0, 7, 4), 'tachyon cannon': (6, 0, 6), 'warp field meter': (5, 8, 1), 'hyperspace probe': (7, 6, 0)},
{(1, 7, 5): ('tachyon cannon', 'spectrograph'), (2, 8, 0): ('hyperspace probe',), (6, 2, 2): ('hyperspace probe', 'D-EFT'), (4, 2, 3): ('hyperspace probe', 'alien life detector', 'wormhole detector'), (2, 2, 1): ('tachyon cannon', 'wormhole detector', 'warp field meter'), (3, 3, 6): ('wormhole detector', 'tachyon cannon', 'D-EFT'), (6, 8, 5): ('spectrograph', 'hyperspace probe'), (4, 0, 4): ('warp field meter', 'D-EFT'), (1, 2, 3): ('spectrograph', 'wormhole detector'), (8, 8, 7): ('warp field meter',), (6, 7, 2): ('wormhole detector',), (2, 3, 4): ('tachyon cannon', 'QAS-2'), (0, 0, 6): ('alien life detector',), (1, 0, 1): ('wormhole detector',), (3, 7, 4): ('D-EFT', 'tachyon cannon'), (1, 5, 4): ('spectrograph',), (8, 8, 8): ('QAS-2',), (3, 8, 8): ('tachyon cannon', 'QAS-2'), (0, 0, 1): ('alien life detector', 'warp field meter', 'spectrograph'), (3, 5, 0): ('tachyon cannon', 'D-EFT'), (8, 2, 1): ('spectrograph',), (8, 0, 0): ('spectrograph', 'QAS-2')},
{'Apollo': (3, 0, 1), 'Rama': (0, 8, 6), 'Galactica': (7, 8, 5), 'Enterprise': (6, 3, 3), 'Rocinante': (2, 0, 3), 'Millennium Falcon': (4, 7, 8), 'Soyuz': (0, 0, 7)},
((-1, 6, 4), (-1, 0, 8), (3, -1, 5), (6, -1, 4), (-1, 6, 6), (-1, 2, 0), (5, 5, -1), (-1, 4, 1), (4, -1, 7), (-1, 2, 7), (-1, 1, 8), (5, -1, 6), (-1, 3, 1), (2, 1, -1), (-1, 4, 2), (3, 6, -1)),
162,
418,
)
]
